import {
  BarChart3,
  Bell,
  CreditCard,
  Crown,
  Gauge,
  Mail,
  MessageCircle,
  QrCode,
  ScanLine,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Ticket,
  UserPlus,
  Users,
  UsersRound,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Mapea el nombre kebab-case usado en los datos mockeados al ícono lucide-react correspondiente. */
export const iconMap: Record<string, LucideIcon> = {
  ticket: Ticket,
  crown: Crown,
  users: Users,
  "qr-code": QrCode,
  zap: Zap,
  bell: Bell,
  sparkles: Sparkles,
  "user-plus": UserPlus,
  smartphone: Smartphone,
  "shield-check": ShieldCheck,
  gauge: Gauge,
  "message-circle": MessageCircle,
  mail: Mail,
  "scan-line": ScanLine,
  "credit-card": CreditCard,
  "users-round": UsersRound,
  "bar-chart-3": BarChart3,
};
